- GDPR12:
  - table: BANK_ACCT
    columns:
    - ACCT_WRDNG_TXT:
        active: N
        masking-value: '***'
    - BANK_ACCT_TXT:
        active: N
        masking-value: ''
  - table: BNFTS_DCSN
    columns:
    - BNFTS_DCSN_NOTE_TXT:
        active: N
        masking-value: ''
  - table: CMMNCTN
    columns:
    - CMMNCTN_ANOTATN_TXT:
        active: N
        masking-value: ''
    - CMMNCTN_ID_TXT:
        active: N
        masking-value: ''
  - table: CMMNCTN_USE
    columns:
    - CMMNCTN_USE_TXT:
        active: N
        masking-value: ''
  - table: CNSLT
    columns:
    - CNSLT_NOTE_TXT:
        active: N
        masking-value: ''
  - table: COMPLAINT
    columns:
    - COMPLAINT_SUBJ_DESC:
        active: N
        masking-value: ''
  - table: DOC
    columns:
    - DOC_CLSFCTN_AD_TXT:
        active: N
        masking-value: ''
    - DOC_CLSFCTN_TXT:
        active: N
        masking-value: ''
    - DOC_DESC:
        active: N
        masking-value: ''
    - ENVLP_ID_TXT:
        active: N
        masking-value: ''
    - ENVLP_PART_TXT:
        active: N
        masking-value: ''
    - FILE_NM:
        active: N
        masking-value: ''
    - INDXNG_NOTE_TXT:
        active: N
        masking-value: ''
    - SNDR_OR_RCPNT_NM:
        active: N
        masking-value: ''
    - SUBJ_NM:
        active: N
        masking-value: ''
  - table: FRGN_TAX_ID
    columns:
    - FRGN_TAX_NO:
        active: N
        masking-value: ''
  - table: HLTH_STTS
    columns:
    - HLTH_STTS_DESC:
        active: N
        masking-value: ''
  - table: ID_DOC
    columns:
    - ID_NO:
        active: N
        masking-value: ''
  - table: NAT_PRSN
    columns:
    - ANNUT_NO:
        active: N
        masking-value: ''
    - BIRTH_DT:
        active: N
        masking-value: ''
    - BIRTH_NM:
        active: N
        masking-value: ''
    - FIRST_NM:
        active: N
        masking-value: ''
    - FIRST_PRSNL_INTEREST_CD:
        active: N
        masking-value: ''
    - INTEREST_DESC:
        active: N
        masking-value: ''
    - LAST_NM:
        active: N
        masking-value: ''
    - MDDL_NM:
        active: N
        masking-value: ''
    - SCND_PRSNL_INTEREST_CD:
        active: N
        masking-value: ''
    - SOCIAL_SCRTY_NO:
        active: N
        masking-value: ''
    - TAX_ID_NO:
        active: N
        masking-value: ''
    - THRD_PRSNL_INTEREST_CD:
        active: N
        masking-value: ''
  - table: NPS
    columns:
    - NPS_DSGNTN_TXT:
        active: N
        masking-value: ''
    - NPS_SCND_CALL_RSLT_DESC:
        active: N
        masking-value: ''
  - table: OCC_DESC
    columns:
    - OCC_ENTR_DESC:
        active: N
        masking-value: ''
  - table: PRSN
    columns:
    - LETTER_SALUTN_TXT:
        active: N
        masking-value: ''
    - NM_EXTNSN_MGRTN_TXT:
        active: N
        masking-value: ''
  - table: PRSN_ADDR_UNSTR
    columns:
    - FIRST_ADDR_LN_TXT:
        active: N
        masking-value: ''
    - FOURTH_ADDR_LN_TXT:
        active: N
        masking-value: ''
    - SCND_ADDR_LN_TXT:
        active: N
        masking-value: ''
    - THRD_ADDR_LN_TXT:
        active: N
        masking-value: ''
  - table: PRSN_ASSMNT
    columns:
    - PRSN_ASSMNT_DESC:
        active: N
        masking-value: ''
  - table: PRSN_ASSMNT_GNRC_DTL
    columns:
    - VAL_DT:
        active: N
        masking-value: ''
    - VAL_TXT:
        active: N
        masking-value: ''
    - VAL_WHOLE_NO:
        active: N
        masking-value: ''
  - table: PRSN_GNRC_DTL
    columns:
    - VAL_DT:
        active: N
        masking-value: ''
    - VAL_TXT:
        active: N
        masking-value: ''
    - VAL_WHOLE_NO:
        active: N
        masking-value: ''
  - table: PRSN_TO_PRSN_REL
    columns:
    - ID_TXT:
        active: N
        masking-value: ''
  - table: SEPA_MANDT
    columns:
    - INITL_RGSTR_REF_TXT:
        active: N
        masking-value: ''
    - MANDT_REF_TXT:
        active: N
        masking-value: ''
  - table: TP_CNTRCT
    columns:
    - INS_PRPRTY_DESC:
        active: N
        masking-value: ''
  - table: WEB_PORTAL_GNRC_DTL
    columns:
    - VAL_DT:
        active: N
        masking-value: ''
    - VAL_TXT:
        active: N
        masking-value: ''
    - VAL_WHOLE_NO:
        active: N
        masking-value: ''
